haystack_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from products.views import PhoneListView, autocomplete_phone

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^products/$', PhoneListView.as_view(), name="products"),
    url(r'^search/', include('haystack.urls')),
    url(r'^products/', PhoneListView.as_view(), name='my_search'),
    url(r'^autocomplete_phone/', autocomplete_phone, name='autocomplete')

]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

products/models.py
from django.db import models


class Phone(models.Model):
    OS_CHOICES = (("Android", "Android"),
                  ("iOS", "iOS"))
    MEMORY_CHOICES = (("16", "16 GB"),
                      ("32", "32 GB"),
                      ("64", "64 GB"),
                      ("128", "128 GB"))
    RAM_CHOICES = (("2", "2 GB"),
                   ("3", "3 GB"))
    CAMERA_CHOICES = ((5, "5 MP"),
                      (7, "7 MP"),
                      (12, "12 MP"))
    DISPLAY_CHOICES = (("5.5", '5.5"'),
                       ("4.5", '4.5"'),
                       ("5.0", '5"'))

    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    in_stock = models.BooleanField()
    ram = models.CharField(max_length=5, choices=RAM_CHOICES)
    display = models.CharField(max_length=5, choices=DISPLAY_CHOICES)
    os = models.CharField(max_length=10)
    memory = models.CharField(max_length=5, choices=MEMORY_CHOICES)
    gps = models.BooleanField()
    camera = models.PositiveIntegerField(choices=CAMERA_CHOICES)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from haystack.query import SQ
from haystack.query import SearchQuerySet, EmptySearchQuerySet


class FilterForm(forms.Form):

    OS_CHOICES = (("Android", "Android"),
                  ("iOS", "iOS"))
    RAM_CHOICES = (("2", "2 GB"),
                   ("3", "3 GB"))
    MEMORY_CHOICES = (("16", "16 GB"),
                      ("32", "32 GB"),
                      ("64", "64 GB"),
                      ("128", "128 GB"))
    CAMERA_CHOICES = ((5, "5 MP"),
                      (7, "7 MP"),
                      (12, "12 MP"))
    DISPLAY_CHOICES = (("5.5", '5.5"'),
                       ("4.5", '4.5"'),
                       ("5.0", '5"'))
    name = forms.CharField(required=False, max_length=150)
    price = forms.IntegerField(widget=forms.NumberInput(attrs={"type": "range", "min": 0, "max": 40000}), required=False)
    ram = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=RAM_CHOICES, required=False)
    display = forms.MultipleChoiceField(required=False, choices=DISPLAY_CHOICES, widget=forms.CheckboxSelectMultiple)
    os = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=OS_CHOICES, required=False)
    memory = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=MEMORY_CHOICES, required=False)
    gps = forms.BooleanField(required=False)
    camera = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=CAMERA_CHOICES)

    def __init__(self, *args, **kwargs):
        self.searchqueryset = kwargs.pop('searchqueryset', None)
        self.load_all = kwargs.pop('load_all', False)

        if self.searchqueryset is None:
            self.searchqueryset = SearchQuerySet()

        super(FilterForm, self).__init__(*args, **kwargs)

    def search(self):
        # First, store the SearchQuerySet received from other processing.
        if not self.is_valid():
            return self.no_query_found()

        if not self.is_valid():
            return self.no_query_found()
        sqs = self.searchqueryset.all()
        for field_name in ['ram', 'os', 'memory', 'display', 'camera']:
            if self.cleaned_data[field_name]:
                kwargs = {'{}__{}'.format(field_name, "in"): self.cleaned_data[field_name]}
                sqs = sqs.filter(**kwargs)

        if self.cleaned_data['price'] is not None:
            sqs = sqs.filter(price__lte=self.cleaned_data['price'])

        if self.cleaned_data['gps']:
            sqs = sqs.filter(gps=self.cleaned_data['gps'])

        if self.cleaned_data['name']:
            sqs = sqs.auto_query(self.cleaned_data['name'])

        return sqs


    def no_query_found(self):
        """
        Determines the behavior when no query was found.

        By default, no results are returned (``EmptySearchQuerySet``).

        Should you want to show all results, override this method in your
        own ``SearchForm`` subclass and do ``return self.searchqueryset.all()``.
        """
        return EmptySearchQuerySet()

products/views.py
from django.http.response import JsonResponse
from haystack.generic_views import SearchView
from haystack.query import SearchQuerySet

from products.forms import FilterForm
from products.models import Phone


class PhoneListView(SearchView):
    """My custom search view."""
    form_class = FilterForm
    template_name = 'products/phone_list.html'



def autocomplete_phone(request):
    auto = SearchQuerySet().models(Phone).autocomplete(auto=request.GET.get('phone', ''))
    suggestions = [result.name for result in auto]
    data = {
        'results': suggestions
    }
    return JsonResponse(data)

templates/base.html
<!DOCTYPE html>
<html lang="en" style="margin: 0; padding: 0;">
{% load static %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Title</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>

<div class="container" style="margin-top:20px;">
  {% block content %}

  {% endblock %}
</div>


{% block javascript %}
{% endblock %}
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/products/phone_list.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
  <div class="row">
  <div class="col-md-2 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-9 col-xs-offset-1">
     <form method="GET" action="{% url 'my_search' %}" class="search-form">
       <label for="id_name">Name:</label>{{ from.name.label_tag }}{{ form.name }}
       {{ form.price.label_tag }}
       <div>From 0 To:
         <input style="max-width: 80px;" type="text" id="show-price-input"></div>
       {{ form.price}}
       {{ form.ram.label_tag }}{{ form.ram }}
       {{ form.display.label_tag }}{{ form.display }}
       {{ form.os.label_tag }}{{ form.os }}
       {{ form.memory.label_tag }}{{ form.memory }}
       <div>{{ form.gps.label_tag }}{{ form.gps }}</div>
       {{ form.camera.label_tag }}{{ form.camera }}
       <div>
       </div>
       <input type="submit" value="Search">
     </form>
  <div class="search-results-container">
  </div>
  </div>
  <div class="col-md-9 col-sm-9 col-xs-12">
  <div class="row">
  {% for result in object_list %}

    <div class="col-md-4 col-sm-4 col-xs-12">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">{{result.object.name}}</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group">
          <li class="list-group-item">Price: {{ result.object.price }}</li>
          <li class="list-group-item">In stock: {{ result.object.in_stock }}</li>
          <li class="list-group-item">RAM: {{ result.object.ram }}</li>
          <li class="list-group-item">Display: {{ result.object.display }}</li>
          <li class="list-group-item">OS: {{ result.object.os }}</li>
          <li class="list-group-item">Builtin Memory: {{ result.object.memory }}</li>
          <li class="list-group-item">GPS: {{ result.object.gps }}</li>
          <li class="list-group-item">Camera: {{ result.object.camera }}</li>
        </ul>
      </div>
</div>
    </div>
    {% if forloop.counter|divisibleby:"3" %}
    </div>
    <div class="row">
    {% endif %}

  {% endfor %}
    </div>
  </div>

  </div>
  </div>
      {% endblock %}

templates/search/search.html
{% extends 'base.html' %}
{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.name }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}